Android 28 이하 버전 기기 스토리지 접근 호환성 유지
ParkSangGwon/TedImagePicker pull request #91
Opened 2021-11-04 18:51 UTC by hongbeomi

- 28버전 이하 기기에서만 `WRITE_EXTERNAL_STORAGE` 권한 요구하도록 변경
- 기존 `MedaiUtil`의 `getMediaUri`에서 분기처리하여 Q 버전 미만 기기에서 파일로 처리하는 로직 제거 및 분기 로직 제거
- 28버전 이하 기기에서 `cursor.query`의 `selection` 파라미터 때문에 갤러리 이미지를 제대로 불러오지 못해서 `selection` 파라미터 분기 처리

2022-01-17 13:50 UTC, ParkSangGwon requested changes
@hongbeomi 
`Build.VERSION_CODES.Q`이하 기기에서 
Multi 선택 모드에서
카메라로 촬영한뒤 가져온 이미지를 선택된 이미지로 인식하지 못하는 문제가 있습니다.

2022-01-17 14:12 UTC, ParkSangGwon requested changes

2022-01-17 14:12 UTC, ParkSangGwon commented on tedimagepicker/src/main/java/gun0912/tedimagepicker/util/MediaUtil.kt
> +            val directoryName =
이부분은 OS버전에 따라서 
uri를 `content://`로 가져오느냐 `file://`로 가져오냐로 분리되기 때문에 유지되어야 합니다.
항상 `content://`로 처리되도록 하면 같은 uri에 대해서 다른 path가 나와서 다른 파일인것처럼 인지되어서 이 이슈가 발생합니다.
https://github.com/ParkSangGwon/TedImagePicker/pull/91#pullrequestreview-854420717

2022-01-19 14:49 UTC, merged

2022-01-19 14:49 UTC, ParkSangGwon commented
This PR merged by https://github.com/ParkSangGwon/TedImagePicker/pull/100

2022-01-20 10:38 UTC, hongbeomi commented
제가 리뷰를 늦게 확인했네요. 피드백 감사합니다!